# site details
name: Joel Gross
description: Personal website
url: http://jagj10.github.io

# social profiles.
github: jagj10
twitter: outofdaylight

highlighter: pygments
permalink: /article/:title.html

exclude: [readme.md]
include: [.htaccess]
timezone: America/New_York